### ISSUE TITLE
Add Atom editor developed by GitHub

### ISSUE THREAD

**Issue by jeffrey-omega** [k4m4/terminals-are-sexy#105]
The hackable text editor :atom: https://atom.io developed by GitHub

Cross-platform editing : 
Atom works across operating systems. You can use it on OS X, Windows, or Linux

Built-in package manager : 
Search for and install new packages or start creating your own—all from within Atom.

Etc...

Open Atom editor from command line

**Comment by xMajedz** [comment]
is atom a command line editor ?

**Comment by JoseCage** [comment]
> is atom a command line editor ?

No. @xMajedz [Atom](https://atom.io) is a *GUI* text editor..

Command line editor we have **e.g** vim, nano..

**Comment by a7madgamal** [comment]
I agree with @xMajedz . however, I use different builtin terminals in atom so listing these might be a good idea
https://atom.io/packages/terminal-plus
https://atom.io/packages/atom-terminal
https://atom.io/packages/atom-terminal-panel

**Comment by k4m4** [comment]
Hi @jeffrey-omega. Thank you for your suggestion; however, as mentioned, atom is not a CLI editor. Thanks again!
