### ISSUE TITLE
Add colorls

### ISSUE THREAD

**Issue by athityakumar** [k4m4/terminals-are-sexy#122]
Hey! I'd like to know if [colors](https://github.com/athityakumar/colorls) qualifies to be added to this list. Thanks! 😄

**Comment by athityakumar** [comment]
Ping @k4m4, in case you haven't seen this yet. 😄

**Comment by k4m4** [comment]
Sorry for the delay. Reviewing now. @athityakumar

**Comment by k4m4** [comment]
Done. Thank you for your contribution. :)
