### ISSUE TITLE
Add kitty

### ISSUE THREAD

**Issue by Boot-Error** [k4m4/terminals-are-sexy#145]
[Kitty](https://github.com/kovidgoyal/kitty) is GPU based terminal editor with tabs, windows

**Comment by RedBeard0531** [comment]
Consider this an endorsement. I was about to file the same ticket. It is the only linux terminal I know of to support both reflow on resize and ligatures for fonts like fira code. The GPU perf and keyboard driven "kitten" helpers are a nice bonus!

**Comment by k4m4** [comment]
@Boot-Error, feel free to make a PR.

**Comment by webknjaz** [comment]
Kitty is wonderful :+1:

**Comment by k4m4** [comment]
Closing in favor of #171.
