### ISSUE TITLE
Broken link from "Edit on GitHub" button

### ISSUE THREAD

**Issue by Nklya** [k4m4/terminals-are-sexy#207]
Hello.

I've found that link from "Edit on GitHub" button is broken.
It goes to 
https://github.com/k4m4/terminals-are-sexy/edit/master/docs/index.md, but this file is not available and thus gets 404.

**Comment by Nklya** [comment]
It's still broken 
https://github.com/k4m4/terminals-are-sexy/blob/master/readme.md/index.md

**Comment by k4m4** [comment]
Yep, I noticed. Working on it! Thanks for bringing it up!

**Comment by k4m4** [comment]
Seems that `mkdocs` has the filename `index.md` as its default config and appends it to the end of the directory that you set in your `edit_uri` variable. Looking for a way to change the default filename value to `readme.md`.

**Comment by k4m4** [comment]
Fixed in [2b1767b](https://github.com/k4m4/terminals-are-sexy/commit/2b1767b9c00476aef15b7ac2c66e391ca44e39ba). In conclusion, I feel that the plain `GitHub` link is more appropriate. Thanks again.
