### ISSUE TITLE
Display Ads that support OSS

### ISSUE THREAD

**Issue by k4m4** [k4m4/terminals-are-sexy#267]
- The [`terminalsare.sexy`](https://terminalsare.sexy) website has been gaining a decent amount of impressions each month. This January alone, there were `70.2K` impressions on the site.
- I was wondering whether you guys think it would be a good idea to add [Carbon Ads](https://www.carbonads.net) to the website (possibly on the top/bottom of the table of contents), and donate all proceeds to the [Open Source Collective](https://opencollective.com/opencollective-oss) or possibly [MkDocs](https://www.mkdocs.org/) (the site generator used by `terminalsare.sexy`).
* There are several other open-source repos that use Carbon Ads:
  * [lodash](https://lodash.com/docs)
  * [bootstrap](https://getbootstrap.com/) - [`Why bootstrap shows carbon ads?`](https://github.com/twbs/bootstrap/issues/13678)
  * [BootstrapCDN]() also donates all revenue to the Open Collective - [`Display Ads that support Open Source`](https://github.com/MaxCDN/bootstrapcdn/issues/861)

Any feedback/ideas?

**Comment by styfle** [comment]
If you're looking to support OSS, I would suggest trying https://codefund.io which is an open source project.

**Comment by lirantal** [comment]
I don't really know either of them so both sounds like great options to me and appreciate your kindness to support OSS @k4m4 ❤️

specifically supporting the projects k4m4 uses sounds like great direct feedback to those teams too so I'm all in for that.

**Comment by jarun** [comment]
As long as the ads aren't intrusive and are decent I think it's a good idea. :+1:

**Comment by wsdjeg** [comment]
I'm ok. thanks.

**Comment by unixorn** [comment]
If they aren't intrusive it's probably worth a try.

**Comment by ericholscher** [comment]
Sorry about commenting on an old issue, but I just wanted to follow up here and let you know that we've launched [EthicalAds](https://www.ethicalads.io/publishers/) which is a spiritual successor to CodeFund. I'm not sure if you're looking to switch providers, but we're all [open source](https://github.com/readthedocs/ethical-ad-server/) and are working to support the community here.
