### ISSUE TITLE
Banner has invalid url in README

### ISSUE THREAD

**Issue by LedaThemis** [k4m4/terminals-are-sexy#297]
As you might've noticed the banner in the readme is not rendering:
![image](https://user-images.githubusercontent.com/38331868/149653567-30652358-f505-40ca-b2be-b002ab8929f8.png)
so I went to the wayback machine to try and recover the banner, and I found it here:
![Wayback machine url of terminals-are-sexy's banner](https://web.archive.org/web/20170820201013if_/http://nikolaskama.me/content/images/2017/02/terminals_are_sexy.png)

**Comment by k4m4** [comment]
Thanks for this! Fixed in [c53af64e02a56cd99a119242b07be7fdf5811c48](https://github.com/k4m4/terminals-are-sexy/commit/c53af64e02a56cd99a119242b07be7fdf5811c48).
