### ISSUE TITLE
Add Neovim as a text-editor

### ISSUE THREAD

**Issue by seeARMS** [k4m4/terminals-are-sexy#57]
Neovim is absent from the text-editors section.

**Comment by dkrieger** [comment]
Didn't vim 8 destroy neovim?

**Comment by k4m4** [comment]
Added. :)

**Comment by wsdjeg** [comment]
@dkrieger vim8's new feature is hard to use, I think neovim is better. and here is a post from author of ag
https://geoff.greer.fm/2015/01/15/why-neovim-is-better-than-vim/

@k4m4  I think neovim should have save level as vim or emacs or other editor.
