### ISSUE TITLE
What do you mean "sexy"?

### ISSUE THREAD

**Issue by smonff** [k4m4/terminals-are-sexy#59]
First, it would be useful to know what is supposed to be understood under the *sexy* term. If you are sexually stimulated by a terminal, there is maybe a problem. 

Second, what does CLI have to prove? I can understand that some very good quality tools can create some stimulation in our mind and bodies, and we know that all this is related to something related to sexuality. But, do we need to over-sexualize everything that way?

We got already enough problems in the tech community, please consider the meaning of creating such things.

**Comment by damarusama** [comment]
What a prude take on sexy. 👎

**Comment by dkrieger** [comment]
`tldr sexy`

**Comment by k4m4** [comment]
Here's the definition of the word _sexy_, given by Google:
**sexy**
adjective: sexy; comparative adjective: sexier; superlative adjective: sexiest

1. sexually attractive or exciting.
"sexy French underwear"
synonyms:	sexually attractive, seductive, desirable, alluring, inviting, sensual, sultry, slinky, provocative, tempting, tantalizing; More
antonyms:	undesirable, family
"neither of them was feeling sexy"
synonyms:	aroused, sexually excited, amorous, lustful, passionate; More

2. **very exciting or appealing.**
"business magazines might not seem like the sexiest career choice"
synonyms:	exciting, stimulating, interesting, appealing, intriguing; More
antonyms:	dull, boring

[ Thanks Google :) ]

**Comment by smonff** [comment]
What search engines returns too are thousands of *sexy girls* websites, porn, lingerie, and other hot stuff. My question is: what do you want to say about terminal and command line by qualifying it of sexy? If somebody on HN pointed out that *sexy* could be the new *awesome*  (that was the new *hip*, that was the new *cool*, etc.) my idea about it is that you don't really mean *sexy*, but this word sounded better than another, and have been used as a *joker word*.

As a public project that curates other open projects, please take in consideration the aim of these tools and what they are made for. Do they claim any sexiness? Would you defend in front of creators, maintainers and users of Bash, Ack, Putty, Git or Vim that what you noticed when using their tools is their *sexiness*? By taking a serious look at your list, the keywords that I saw that are the closest from arousing are:

    delightful awesome appeal fancy sexy

The characteristics I think CLI users usually value the most and I can find in your list too are:

    fast portable free cross-platform community-driven minimal powerful configurable
    efficient modern intuitive optimized

It is not prude to complain about the use of this word. There is a large panel of people that can be offended: authors of the tools, anti-sexist activists, religious people, and a various individuals who can feel harassed by the use of these kind of terms.

[![](https://lut.im/AkG7Am9QSe/hZy2zXcVlRaYNpjO)](https://youtu.be/eO0C6dxb7o4)

What I perceive is that you are selling CLI the same way advertisers sells ice creams: they use a mouth sucking a phallic candy to claim that the ice cream is more valuable than what it is. It is basic propaganda for selling products, commonly used for selling cars, lipstick, bags and smartphones. What I don't like in this sexy list is that you add a layer of *sexy branding* on something that don't need any. I am ok with the *curated list* idea around these tools, but seeing this driven by a *sexy concept* seems a bit scary.

For me, sexy is definitely stuck in the "bad" aspects I explained before. As all the communities, tech communities got serious problems with sexism, harassment and rape culture. The fact that this word became so common to describe people, objects, or piece of software in that case, can be considered as preoccupying. More than a question now, I tried to share some point of view about it to help you making your project better, hoping it can help.

**Comment by dkrieger** [comment]
"Sexy" is not inherently problematic, even with reference to a person. _Could_ this "compliment" be used _inappropriately_? Yeah, and it happens to women all the time, unfortunately. The word is not the problem though, it's the context -- making comments on a random woman's (or worse, a business colleague's) sexual appeal is wildly inappropriate, and can also be threatening in certain contexts. However, referring to a regular, consensual sex partner as "sexy" is probably fine (obviously, blurting it out in inappropriate contexts is not fine). Suggesting that referring to inanimate software as "sexy" is sexist is pushing it. I mean, considering that a woman referring to a random man as "sexy" wouldn't be sexist (as men are not an oppressed identity), I'm pretty sure that software isn't an oppressed group either, and therefore it is not sexist to refer to it as sexy. You're essentially saying that the mere reminder that people are sexual is triggering and therefore sexist.

**Comment by damarusama** [comment]
@smonff I think that this fear of 'sexy' is what cause a rape/sexist culture. The lack of any reference to sexuality, excitement and our natural human desire has lead a whole society to fear sex, or label it as a bad thing, which it turn leaves too much in the dark. To be offended by using the word sexy for cli is a proof of a major problem with accepting our sexuality as human. Which in turn creates trauma and creates sex offender. Life is sexy, we are sexual being - and hiding that fact is actually creating the problem. 

Now if he would have named the page Command Line Interface Treasures and used its acronym, then I would have been on your side.

**Comment by dkrieger** [comment]
@damarusama I wouldn't go so far as to say that cultural prudishness _causes_ rape culture or sexism, but it certainly doesn't help for the reason you said: it pushes sexuality into the dark.

**Comment by deathtrip** [comment]
Just close this issue. Let's not feed SJW trolls, who only look for things to be offended by.

**Comment by therealmikz** [comment]
That's one of the stupidest tickets that I've ever seen in my life

**Comment by jaredly** [comment]
perhaps we got off on the wrong foot. (and the OP entering with snark may have set the stage)
My claims:
- the tech industry has a huge sexism problem
- the term "sexy" is frequently used to objectify women
- including terms like "sexy" in coding contexts unintentionally alienates portions of the developer population
- nothing is lost by avoiding it
I do not think that y'all are bad people, or that the alienation is intentional. I don't think that anyone should be punished for using the term "sexy" to refer to something they find awesome/useful/etc. I do think it has unintended consequences.

**Comment by justjanne** [comment]
> including terms like "sexy" in coding contexts unintentionally alienates portions of the developer population

It’s less the terms, and more how they’re used. Most women in tech, me included, have no issue with the terms, but only with them being used to objectify women.

IMO, this is a non-issue.

**Comment by jtdaugherty** [comment]
Although this ticket is closed, I want to add that the use of the word "sexy" in the project name makes me very unlikely to want to contribute or to share this with others, precisely because of the sexism-in-tech and objectification issues that others have raised. Aside from the name, I'm glad this exists, though; I definitely like to promote and use terminal tools when I can.

Please consider changing the name. "Terminals are awesome" would do just as well and avoid the issues with the name.
