### ISSUE TITLE
Easy install was succeeded by pip a while ago

### ISSUE THREAD

**Issue by stuaxo** [k4m4/terminals-are-sexy#66]
Prob best remove it :)

Though if you are doing pip, it's probably worth mentioning Conda as well.

**Comment by k4m4** [comment]
Easy_install has been removed. Thanks for the heads up. :)

**Comment by stuaxo** [comment]
I had a quick look at the webpage for pkgin, and it seems it should be under "universal", though I guess it is more used BSD platforms than Linux

-> scroll to platforms
http://pkgin.net/
